ERROR 2025-04-26 23:59:13,818 log Internal Server Error: /api/error
Traceback (most recent call last):
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\learning\Python\ecommerce\products\views.py", line 94, in test_error
    raise ValueError("This is a test error!")
ValueError: This is a test error!
ERROR 2025-04-26 23:59:13,822 basehttp "GET /api/error HTTP/1.1" 500 63536
ERROR 2025-04-27 00:00:07,138 log Internal Server Error: /api/error
Traceback (most recent call last):
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\learning\Python\ecommerce\products\views.py", line 94, in test_error
    raise ValueError("This is a test error!")
ValueError: This is a test error!
ERROR 2025-04-27 00:00:07,140 basehttp "GET /api/error HTTP/1.1" 500 63536
ERROR 2025-04-27 13:44:39,346 log Internal Server Error: /api/test
Traceback (most recent call last):
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sivaprakash.rangasam\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\learning\Python\ecommerce\products\views.py", line 113, in test
    print(order.products.all())
          ^^^^^^^^^^^^^^
AttributeError: 'Orders' object has no attribute 'products'. Did you mean: 'product'?
ERROR 2025-04-27 13:44:39,354 basehttp "GET /api/test HTTP/1.1" 500 96842
